# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hanxiao/xtnc/rnd/mdpe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hanxiao/xtnc/rnd/mdpe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hanxiao/xtnc/rnd/mdpe/CMakeFiles /Users/hanxiao/xtnc/rnd/mdpe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hanxiao/xtnc/rnd/mdpe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mdpe

# Build rule for target.
mdpe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mdpe
.PHONY : mdpe

# fast build rule for target.
mdpe/fast:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/build
.PHONY : mdpe/fast

#=============================================================================
# Target rules for targets named ibc

# Build rule for target.
ibc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ibc
.PHONY : ibc

# fast build rule for target.
ibc/fast:
	$(MAKE) -f IBClient/source/CppClient/client/CMakeFiles/ibc.dir/build.make IBClient/source/CppClient/client/CMakeFiles/ibc.dir/build
.PHONY : ibc/fast

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/Main.cpp.s
.PHONY : Main.cpp.s

src/Helpers/Topics.o: src/Helpers/Topics.cpp.o

.PHONY : src/Helpers/Topics.o

# target to build an object file
src/Helpers/Topics.cpp.o:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Helpers/Topics.cpp.o
.PHONY : src/Helpers/Topics.cpp.o

src/Helpers/Topics.i: src/Helpers/Topics.cpp.i

.PHONY : src/Helpers/Topics.i

# target to preprocess a source file
src/Helpers/Topics.cpp.i:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Helpers/Topics.cpp.i
.PHONY : src/Helpers/Topics.cpp.i

src/Helpers/Topics.s: src/Helpers/Topics.cpp.s

.PHONY : src/Helpers/Topics.s

# target to generate assembly for a file
src/Helpers/Topics.cpp.s:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Helpers/Topics.cpp.s
.PHONY : src/Helpers/Topics.cpp.s

src/Nodes/Node.o: src/Nodes/Node.cpp.o

.PHONY : src/Nodes/Node.o

# target to build an object file
src/Nodes/Node.cpp.o:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/Node.cpp.o
.PHONY : src/Nodes/Node.cpp.o

src/Nodes/Node.i: src/Nodes/Node.cpp.i

.PHONY : src/Nodes/Node.i

# target to preprocess a source file
src/Nodes/Node.cpp.i:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/Node.cpp.i
.PHONY : src/Nodes/Node.cpp.i

src/Nodes/Node.s: src/Nodes/Node.cpp.s

.PHONY : src/Nodes/Node.s

# target to generate assembly for a file
src/Nodes/Node.cpp.s:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/Node.cpp.s
.PHONY : src/Nodes/Node.cpp.s

src/Nodes/StreamingNode.o: src/Nodes/StreamingNode.cpp.o

.PHONY : src/Nodes/StreamingNode.o

# target to build an object file
src/Nodes/StreamingNode.cpp.o:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/StreamingNode.cpp.o
.PHONY : src/Nodes/StreamingNode.cpp.o

src/Nodes/StreamingNode.i: src/Nodes/StreamingNode.cpp.i

.PHONY : src/Nodes/StreamingNode.i

# target to preprocess a source file
src/Nodes/StreamingNode.cpp.i:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/StreamingNode.cpp.i
.PHONY : src/Nodes/StreamingNode.cpp.i

src/Nodes/StreamingNode.s: src/Nodes/StreamingNode.cpp.s

.PHONY : src/Nodes/StreamingNode.s

# target to generate assembly for a file
src/Nodes/StreamingNode.cpp.s:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/StreamingNode.cpp.s
.PHONY : src/Nodes/StreamingNode.cpp.s

src/Nodes/SubscriberNode.o: src/Nodes/SubscriberNode.cpp.o

.PHONY : src/Nodes/SubscriberNode.o

# target to build an object file
src/Nodes/SubscriberNode.cpp.o:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/SubscriberNode.cpp.o
.PHONY : src/Nodes/SubscriberNode.cpp.o

src/Nodes/SubscriberNode.i: src/Nodes/SubscriberNode.cpp.i

.PHONY : src/Nodes/SubscriberNode.i

# target to preprocess a source file
src/Nodes/SubscriberNode.cpp.i:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/SubscriberNode.cpp.i
.PHONY : src/Nodes/SubscriberNode.cpp.i

src/Nodes/SubscriberNode.s: src/Nodes/SubscriberNode.cpp.s

.PHONY : src/Nodes/SubscriberNode.s

# target to generate assembly for a file
src/Nodes/SubscriberNode.cpp.s:
	$(MAKE) -f CMakeFiles/mdpe.dir/build.make CMakeFiles/mdpe.dir/src/Nodes/SubscriberNode.cpp.s
.PHONY : src/Nodes/SubscriberNode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mdpe"
	@echo "... ibc"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... src/Helpers/Topics.o"
	@echo "... src/Helpers/Topics.i"
	@echo "... src/Helpers/Topics.s"
	@echo "... src/Nodes/Node.o"
	@echo "... src/Nodes/Node.i"
	@echo "... src/Nodes/Node.s"
	@echo "... src/Nodes/StreamingNode.o"
	@echo "... src/Nodes/StreamingNode.i"
	@echo "... src/Nodes/StreamingNode.s"
	@echo "... src/Nodes/SubscriberNode.o"
	@echo "... src/Nodes/SubscriberNode.i"
	@echo "... src/Nodes/SubscriberNode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

